using System;
using System.Collections.Generic;
using System.Text;

namespace A_star_Search_Algorithm
{
    class Map
    {
        public List<String> GenerateMap()
        {
            // G = Grama, Custo: 5
            // P = Paralelepipedo, Custo: 10
            // A = Asfalto, Custo: 1
            // E = Edificio, Custo: 0
            // T = Terra, Custo: 3
            // F = Amigo da barbie
            // B = Barbie
            List<string> map = new List<string>
            {
                "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
                "GGPPPPPPPPPPPPPPGGGGPPPPPAGGGGGGGGGGGGGGGG",
                "GGPEEEEEPEEEEEEPGGGGPEEEGAGGGPPPPPPPPPPPGG",
                "GGPEEEEEPEEEEEEPPPPPPEEAAAGGGPGGGGGGGGGPGG",
        /*05*/  "GGPEEPEEPEEEFEEPEEEEGEEAAAGGGPGGGTTTGGGPGG",
                "GGPPPPPPPPPPPPPPPEEEGEEEGAGGGPGGGTFTGGGPGG",
                "GGPTTTTTTTTTTTTPPEEEGGGGGAGGGPGGGTTTGGGPGG",
                "GGPTTTTTTTTTTTTPEEEEGEEEGAGGGPGGGTTTGGGPGG",
                "GGPTTTTGGGGTTTTPPPPPPEEEGAGGGPGGGGGGGGGPGG",
        /*10*/  "GGPTTTTGFGGTTTTPGGGGPEEAAAGGGPPPPPPPPPPPGG",
                "GGPTTTTGGGGTTTTPGGGGPEEEGAGGGGGGGGPGGGGGGG",
                "GGPTTTTTTTTTTTTPGGGGPEEEGAGGGGGGGGPGGGGGGG",
                "GGPTTTTTTTTTTTTPGGGGPGGGGAGGGGGGGGPGGGGGGG",
                "GGPPPPPPPPPPPPPPAAAAAAAAAAAAAAAAAAAAAAAAAA",
        /*15*/  "GGAGGGGGGGGGGGGAGGGGGGGGGAGGGGGGGGGGGGGGGG",
                "GGAGEEEGGEEEEGGAGEEEEEEEGAGEEEEEEEGEEEEEGG",
                "GGAPPEEGGEEEAAAAGEEEEEEEGAGEEEEEEEGEEEEEGG",
                "GGAGEEEGGEEEEGGAGEAEEEAEGAGEEEEAEEGEEAEEGG",
                "GGAGGGGGGGGGGGGAGGAGGGAGGAGGGGGAGGGGGAGGGG",
        /*20*/  "GGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGG",
                "GGAPPPPPPAGGGGGGGGGGAGGGAGGGGGAGGAGPGGGAGG",
                "GGAPEEEEPAGEEEGGEEEGAGEEAEGEEGAGEAEPEEGAGG",
                "GGAPEEEEPAGEEEGGEEBAAGEEEEGEEGAGEEEPEEGAGG",
                "GGAPEEEPPAAAEEGGEEEGAGGGGGGEAAAGGGGPEFAAGG",
        /*25*/  "GGAPEEEEPAGEEEGGEEEGAGEEEEGEEGAGEEEPEEGAGG",
                "GGAPEEEEPAGEEEGGEEEGAGEEAEGEEGAGEAEPEEGAGG",
                "GGAPPPPPPAGGGGGGGGGGAGGGAGGGGGAGGAGPGGGAGG",
                "GGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGG",
                "GGAGGGGGGGGAGGGGPGAGPGGGPGAGGGAGGGGPGGGAGG",
        /*30*/  "GGAGEEEEEEGAGEEEPEAEPEEEPEAEGGAGEEEPEEGAGG",
                "GGAGEEAAEEGAGEAEPEEEPEAEPEEEGGAGEEEEEEGAGG",
                "GGAGGGAAGGGAGGAGPGGGPGAGPGGGGGAGGGGGGGGAGG",
                "GGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGG",
                "GGAGGGGGGGGGGGGGGGGGAGGGGGGPGGGGGGGPPPPAGG",
        /*35*/  "GGAGEEEEEEEEEEEEEEEGAGGGGGGPGGGGGGGPEEPAGG",
                "GGAGEAAAAAAAEEFAAEEGAGGGGGGPGGGGGGGPEEPAGG",
                "GGAGEAEEEEEAEEEEAEEGAPPPPPPPPPPPPPPPFEPAGG",
                "GGAGEAAAAEEAAAAAAEEGAGGGGGGPGGGGGGGPEEPAGG",
                "GGAGEEEEAEEEEEEEEEEGAGGGGGGPGGGGGGGPEEPAGG",
        /*40*/  "GGAGGGGGAGGGGGGGGGGGAGGGGGGPGGGGGGGPPPPAGG",
                "GGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGG",
                "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"

            };

            return map;
        }

        

    }
}
